POINT('foo',10 20);
POINT('foo',1.0, 20);
POINT('foo',10 ,-2.0);
SELECTTOP 100 * FROM my_table1;
SELECT TOP100 * FROM my_table1;
SELECT TOP 100* FROM my_table1;
SELECT TOP hundred * FROM my_table1;
SELECT DISTINCT sin FROM my_table1;
SELECT TOP 100 FROM my_table1;
SELECT * FROM my_table1 where x in(10,20,30);
SELECT * FROM my_table1 where x not in(10,20,30);
SELECT FROM my_table1 WHERE CONTAINS(POINT('J2000',10 , 20),CIRCLE('J2000',10 , 20,1));
SELECT * FROM WHERE CONTAINS(POINT('J2000',10 , 20),CIRCLE('J2000',10 , 20,1));
1= CONTAINS(POINT('J2000',my_table1.ra,dec),CIRCLE('J2000',+10 , -20,-1)) And x<1 And x>2 Or y < 3 Or y >5SELECT *,ra FROM my_table1;
SELECT my_tablel1.* as ra_dec FROM my_table1;
select sum(a,b) from a;
select sum from a;
select sum( from a;
select abs(a,b) from a;
select sin from a;
select sin() from a;
select sin( from a;
select atan2 from a;
select atan2() from a;
select atan2(a) from a;
select atan2(a,) from a;
select atan2(a,b from a;
select round from a;
select round() from a;
select round(a,) from a;
select round(a,b from a;
select round(a,10 from a;
select count(* from a;
select b from a where x<1 groupby a;
select b from a where x<1 group bya;
select b from a where x<1 orderby a;
select b from a where x<1 order bya;
select b from a where x<1 havinga;
select a asb from a group by a;
Select fromage ast from fromming;
SELECT * FROM my_table1 where (x notBetween 2 AND 4);
SELECT * FROM my_table1 where x notin (10,20,30);
SELECT * FROM mytable WHERECONTAINS(POINT('J2000',mytable.ra,dec),CIRCLE('J2000',+10 , -20,-1)) = 1;
SELECT * FROM mytable as my WHERECONTAINS(POINT('J2000',mytable.ra,dec),CIRCLE('J2000',+10 , -20,-1)) = 1;
SELECT * from TAP_UPLOAD.wrong_table;
SELECT TAP_UPLOAD.* from TAP_UPLOAD.mytable;
SELECT TAP_UPLOAD.wrong_table from TAP_UPLOAD.mytable;
select CASE foo WHENever THEN 'c' END from b;
select alligator from (table1);
